Add runbook
Financial-Times/public-people-api pull request #42
Opened 2020-10-12 08:51 UTC by bboykov

# Description

## What

Add runbook for the service.

## Why

[JIRA ticket](https://financialtimes.atlassian.net/browse/UPPSF-1181).

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [X] Documentation
- [ ] Breaking change
- [X] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2020-10-13 07:45 UTC, karsov requested changes
The dependency on `public-concepts-api` is missing.

2020-10-13 07:45 UTC, karsov commented on runbooks/runbook.md
> +<https://github.com/Financial-Times/public-people-api>
This is a public API, its URL is:
```suggestion
<https://api.ft.com/people>
```

2020-10-13 07:45 UTC, karsov commented on runbooks/runbook.md
> +- georgi.ivanov
I'm not really sure if the content team knows about this service.

2020-10-13 07:45 UTC, karsov commented on runbooks/runbook.md
> +The service is deployed in the delivery clusters as a deployment.
The failover details are missing.
```suggestion
The service is deployed in both Delivery clusters. The failover guide for the cluster is located here: https://github.com/Financial-Times/upp-docs/tree/master/failover-guides/delivery-cluster
```

2020-10-13 07:45 UTC, karsov commented on runbooks/runbook.md
> +- <https://upp-prod-delivery-us.upp.ft.com/__health/__pods-health?service-name=public-people-api>
To make it look like the other runbooks:
```suggestion
Service in UPP K8S delivery clusters:

- Delivery-Prod-EU health: <https://upp-prod-delivery-eu.upp.ft.com/__health/__pods-health?service-name=public-people-api>
- Delivery-Prod-US health: <https://upp-prod-delivery-us.upp.ft.com/__health/__pods-health?service-name=public-people-api>
```

2020-10-13 09:03 UTC, karsov commented on runbooks/runbook.md
> +related data given a Person identifier.
There is a warning in the runbook validator about multiple lines in the description:
```suggestion
The Public People API is a micro-service which aims to provide Person and related data given a Person UUID identifier.
```

2020-10-13 09:09 UTC, karsov approved these changes

2020-10-20 06:15 UTC, ivan-p-nikolov approved these changes

2020-10-20 06:17 UTC, merged